dubimobi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'gudlet.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('mobile.urls')),
    url(r'^mobile/', include('mobile.urls', namespace="mobile")),
    url(r'^admin/', include(admin.site.urls)),
]

mobile/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^search', views.search, name='search'),
    #url(r'^search', views.SearchView.as_view(), name='search'),
    #url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mobile/models.py
import datetime
from django.utils import timezone
from django.db import models

# Create your models here.
class Condition(models.Model):
	 name = models.CharField(max_length=15)
	 def __unicode__(self):
		return self.name
class Operatingsystem(models.Model):
	name = models.CharField(max_length=15)
	version = models.CharField(max_length=15)
	def __unicode__(self):
		return self.name
class  Mobile(models.Model):
	name = models.CharField(max_length=15)
	price = models.FloatField(default=0.0)
	operatingsystem = models.ForeignKey(Operatingsystem)
	condition = models.ForeignKey(Condition)
	photo = models.ImageField(upload_to='media/mobile')
	pub_date = models.DateTimeField('date published')
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
	def __unicode__(self): #Change to __str(self) on Python 3
		return self.name



#class Seller(models.Model):
#   name = models.CharField(max_length=15)
#	shop_id =
#	conatct_phone =
#	contact_email =
#
#	pub_date = models.DateTimeField('date published')
#	def __unicode__(self):
#		return self.name
#class Gudlet(models.Model):
#	name = models.CharField(max_length=15)
#	pub_date = models.DateTimeField('date published')
#	actual_price = models.FloatField(default=0.0)
#	offer_price = models.FloatField(default=0.0)
#	category = models.ForeignKey(Category)
#	available_at_shops = models.ForeignKey(Shop)
#	def was_published_recently(self):
#		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
#	def __unicode__(self):
#		return self.name

mobile/views.py
import json, requests
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Mobile


class IndexView(generic.ListView):
    template_name = 'mobile/index.html'
    context_object_name = 'latest_mobile_list'

    def get_queryset(self):
        """Return the last five published mobiles."""
        return Mobile.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Mobile
    template_name = 'mobile/detail.html'
def search(request):
	search_query = '*' + request.GET.get('q') + '*'
	data = {
    "query": {
        "query_string": { "query": search_query }
    	}
	}
	response = requests.post('http://127.0.0.1:9200/dubimobi_index/mobile/_search', data=json.dumps(data))
	#response_ex = [res['_source']['name'] for res in response.json()['hits']['hits'] ]
	search_result_ids = [res['_id'] for res in response.json()['hits']['hits'] ]
	search_result_data = Mobile.objects.filter(id__in=search_result_ids)
	return render(request, 'mobile/search.html', {'search_result_data': search_result_data})
	#print response.json()


#class SearchView(generic.DetailView):
#    model = Mobile
#    template_name = 'mobile/search.html'


#class ResultsView(generic.DetailView):
#   model = Mobile
#    template_name = 'mobile/results.html'

mobile/templates/mobile/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'mobile/img/favicon.ico' %}">

    <title>Sell | buy mobiles</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'mobile/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'mobile/css/jumbotron.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'mobile/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Dubimobi</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <!--
    <div class="jumbotron">
      <div class="container">
        <h1>Welcome!</h1>
        <p>Dubimobi is a marketplace for used and new mobiles. Individulas can post  an used mobile listing for free. Business users who wants to sell new or usesd mobiles, please contact us for creating a free account for 3 months</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>
    -->
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
      {% block content%}{% endblock %}
      </div>
      <hr>

      <footer>
        <p>&copy; Dubimobi 2015</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'mobile/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'mobile/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

mobile/templates/mobile/detail.html
{% extends 'mobile/base.html' %}
{% load staticfiles %}
{% block content %}
<img src="{{mobile.photo.url}}" alt="Mobile image" height="300" width="300"/>
{{ mobile }} AED {{ mobile.price}}
 {{ mobile.operatingsystem}}
{% endblock %}

mobile/templates/mobile/detail.html-2015-05-06.html
{% load staticfiles %}
<img src="{{mobile.photo.url}}" alt="Mobile image" height="300" width="300"/>
<br>
{{ mobile }} {{ mobile.price}} 

mobile/templates/mobile/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'mobile/img/favicon.ico' %}">

    <title>Sell | buy mobiles</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'mobile/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'mobile/css/jumbotron.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'mobile/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Dubimobi</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form role="form" action="/mobile/search" class="navbar-form navbar-right">
            <div class="form-group">
              <input type="search" name="q" id="query" class="form-control" placeholder="Search" />
            </div>
              <input type="submit" name="commit" value="Search" class="btn btn-success" />
                             <!--<a class="btn btn-danger navbar-btn navbar-right" href="#">Sell</a> -->
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Welcome!</h1>
        <p>Dubimobi is a marketplace for used and brand new mobiles. Individuals can list their used mobile phone for free. Business users who want to sell new or/and used mobiles, please contact us for creating a free account for 3 months</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Contact Us &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        {% block content %}
    {% if  latest_mobile_list %}
    
      {% for mobile in latest_mobile_list %}
        <div class="col-md-4">
          <h2>{{ mobile.name }}</h2>
          <img src="{{mobile.photo.url}}" alt="Mobile image" height="300" width="300"/>
          <h1>{{ mobile.price }}</h1>
          <p>Description </p>
          <p><a class="btn btn-default" href="{% url 'mobile:detail' mobile.id %}" role="button">View details &raquo;</a></p>
        </div>
      {% endfor %}
    {% else %}
      <p> No Mobiles are available </p>
    {% endif %}
  {% endblock %}
      </div>

      <hr>

      <footer>
        <p>&copy; Dubimobi 2015</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'mobile/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'mobile/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

mobile/templates/mobile/search.html
{% extends 'mobile/base.html' %}
	{% block content %}
		{% if search_result_data %}
		
 			{% for mobile in search_result_data %}
 				<div class="col-md-4">
 					<h2>{{ mobile.name }}</h2>
 					<img src="{{mobile.photo.url}}" alt="Mobile image" height="300" width="300"/>
 					<h1>{{ mobile.price }}</h1>
 					<p>Description </p>
 					<p><a class="btn btn-default" href="{% url 'mobile:detail' mobile.id %}" role="button">View details &raquo;</a></p>
 				</div>
 			{% endfor %}
 		{% else %}
 			<p> No Mobiles are available </p>
 		{% endif %}
 	{% endblock %}

mobile/templates/mobile/search.html-1.html
{% extends 'mobile/base.html' %}
{% block content %}
{% if search_result_data %}
  {% for mobile in search_result_data %}
  <div cass="col-md-4">
          <h2>{{ mobile.name }}</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="{% url 'mobile:detail' mobile.id %}" role="button">View details &raquo;</a></p>
        </div>
  {% endfor %}
{% else %}
<p> No Mobiles are available </p>
{% endif %}
{% endblock %}

mobile/templates/mobile/search.html-cpd.html
{% extends 'mobile/base.html' %}
{% block content %}
{% if search_result_data %}
  {% for mobile in search_result_data %}
  <div cass="col-md-4">
          <h2>{{ mobile.name }}</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="{% url 'mobile:detail' mobile.id %}" role="button">View details &raquo;</a></p>
        </div>
  {% endfor %}
{% else %}
<p> No Mobiles are available </p>
{% endif %}
{% endblock %}